[package]
license = ["Apache-2.0"]
keywords = ["News API", "Headlines", "Articles", "News"]
org = "ballerinax"
name = "jira"
version = "0.1.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
